# Матрицы и векторы

Подключаем необходимые библиотеки:
```python
from numpy import *
from matplotlib.pyplot import *
```

Все это (и даже больше) делает magic-команда
```python
%pylab
```

Лучше поступать так:
```python
import numpy as np
import matplotlib.pyplot as plt
```

Вместо этого можно выполнить команду
```python
%pylab --no-import-all
```

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Создание массива (вектора)

In [2]:
x = [1, 2, 3, 2, 3, 4]
type(x)

list

In [3]:
x = np.array((1, 2.0, -1))
print(x)

[ 1.  2. -1.]


In [4]:
print(type(x))
print(x.ndim)  # Количество размерностей массива
print(x.shape) # Размеры
print(x.dtype) # Тип элементов

<class 'numpy.ndarray'>
1
(3,)
float64


In [5]:
x = np.array([1, 2, -1], dtype = 'str')
print(x)

['1' '2' '-1']


In [6]:
print(type(x))
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(3,)
<U2


## Двумерные массивы

In [7]:
A = np.array([[1, 2, 3], [4, 1, 6], [7, 2, 0]])
print(A)

[[1 2 3]
 [4 1 6]
 [7 2 0]]


In [8]:
#A = [1, 2, 3; 4, 1, 6; 7, 2, 0] # А так в MATLAB

In [9]:
print(type(A))
print(A.ndim)
print(A.shape)
print(A.dtype)

<class 'numpy.ndarray'>
2
(3, 3)
int64


## Элементы и срезы

In [10]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
A[1]

array([5, 6, 7, 8])

In [12]:
A[1][2]

7

In [13]:
A[1, 2] # То же самое

7

In [14]:
A[1, 3] = 333
A

array([[  1,   2,   3,   4],
       [  5,   6,   7, 333],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [15]:
A[1:4, 0:2] # не так: A[1:4][0:2]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [16]:
A[1:4]

array([[  5,   6,   7, 333],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [17]:
A[1:3]

array([[  5,   6,   7, 333],
       [  9,  10,  11,  12]])

In [18]:
B = A[1:4]
B[0:2]

array([[  5,   6,   7, 333],
       [  9,  10,  11,  12]])

In [19]:
A[1:4, 0:2] = [[1, 3], [5, 0], [0, 0]]
print(A)

[[  1   2   3   4]
 [  1   3   7 333]
 [  5   0  11  12]
 [  0   0  15  16]]


In [20]:
B = A[1:4:2, ::2]
B

array([[ 1,  7],
       [ 0, 15]])

In [21]:
B = A[1:4, 0:2]
B[1, 0] = 555    # Меняет и массив A (в отличие от срезов в списках) 
A

array([[  1,   2,   3,   4],
       [  1,   3,   7, 333],
       [555,   0,  11,  12],
       [  0,   0,  15,  16]])

In [22]:
x = np.array([1, 2, -3, 4, -2, 2])
#y = np.array([-1, 0, -3, 4, -2, 1])
x > 0

array([ True,  True, False,  True, False,  True])

In [23]:
x[np.array([ True,  True, False,  True, False,  True], dtype='bool')]

array([1, 2, 4, 2])

In [24]:
x[x > 0] = 111
x

array([111, 111,  -3, 111,  -2, 111])

In [25]:
A = np.array([[1,  2, -3], [4, -2,  2]])
A

array([[ 1,  2, -3],
       [ 4, -2,  2]])

In [26]:
A > 0

array([[ True,  True, False],
       [ True, False,  True]])

In [27]:
A[:, 2:]

array([[-3],
       [ 2]])

In [28]:
B = A[A > 0]
print(B)

[1 2 4 2]


In [29]:
A

array([[ 1,  2, -3],
       [ 4, -2,  2]])

In [30]:
a = 11*np.array(range(0, 10))
print(a)
print(a[[1, 3, 5]])   # Так тоже можно выделять подмассивы (со списками этот фокус не прокатит)

[ 0 11 22 33 44 55 66 77 88 99]
[11 33 55]


In [31]:
np.arange(0, 10) # эквивалентно np.array(range(0, 10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
color = np.array(['red', 'blue'])
color[[1, 0, 1, 0, 1, 0]]
#type(color)
#color.dtype

array(['blue', 'red', 'blue', 'red', 'blue', 'red'], dtype='<U4')

## Создание векторов и матриц

In [33]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(2, 10, .3)

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6,
       5.9, 6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. , 8.3, 8.6, 8.9, 9.2, 9.5,
       9.8])

In [35]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.random.seed(42) # use random.seed() to randomize
np.random.rand(2, 3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [37]:
np.random.rand(3, 5)

array([[0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449],
       [0.96990985, 0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914, 0.61185289]])

In [38]:
a = -1
b = 1
np.random.rand(2, 5)*(b-a) + a

array([[-0.72101228, -0.4157107 , -0.26727631, -0.08786003,  0.57035192],
       [-0.60065244,  0.02846888,  0.18482914, -0.90709917,  0.2150897 ]])

In [39]:
np.random.uniform(-1, 1, (2, 5))

array([[-0.65895175, -0.86989681,  0.89777107,  0.93126407,  0.6167947 ],
       [-0.39077246, -0.80465577,  0.36846605, -0.11969501, -0.75592353]])

In [40]:
np.random.randint(0, 10)

7

In [41]:
np.random.randint(0, 10, (3, 5))

array([[2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1]])

In [42]:
np.random.randn(5) # Нормальная случайная величина с мат.ожиданием - 0, сигма = 1

array([ 0.69839894, -0.17162884, -0.90718658,  1.18862573,  0.78553212])

In [43]:
sigma = 3;
mu = 5
sigma * np.random.randn(5) + mu 

array([12.96803027,  5.79045812,  9.92531335,  6.3824489 ,  5.25777041])

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
Z = np.zeros([3, 5])
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [47]:
I = np.ones((2, 4))
print(I)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
E = np.eye(3, 6)
print(E)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


## Манипулирование с матрицами

In [50]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [51]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [52]:
np.array([1, 2, 3]) / np.array([4, 5, 6])

array([0.25, 0.4 , 0.5 ])

In [53]:
3 * [1, 2, 3]

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [54]:
3 * np.array([1, 2, 3])

array([3, 6, 9])

In [55]:
np.array([1, 2, 3]) / 5.0

array([0.2, 0.4, 0.6])

In [56]:
np.array([1, 2, 3]) + 5.0

array([6., 7., 8.])

In [57]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

In [58]:
x = np.linspace(-np.pi, np.pi, 20)
2 * np.sin(x) + x ** 2

array([ 9.8696044 ,  7.25175251,  4.92299006,  2.94606356,  1.36929402,
        0.22134059, -0.49190506, -0.78795721, -0.70583817, -0.30184956,
        0.3565288 ,  1.19795141,  2.15493843,  3.17118825,  4.20767856,
        5.24689508,  6.29472948,  7.37984091,  8.55055038,  9.8696044 ])

In [59]:
a = np.arange(1, 13)
print(a)
A = a.reshape((3, 4))
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [60]:
a[0] = 5

In [61]:
A

array([[ 5,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
A[2, 1] = 111
a

array([  5,   2,   3,   4,   5,   6,   7,   8,   9, 111,  11,  12])

In [63]:
A = np.arange(1, 7).reshape([2, 3])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
B = (11 * np.arange(1, 7)).reshape([2, 3])
B

array([[11, 22, 33],
       [44, 55, 66]])

In [65]:
a = np.array([1, 2, 3])
b = np.concatenate([a, a, a])

In [66]:
a[0] = 33

In [67]:
b

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [68]:
np.concatenate([A, A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
print(A)
print(B)
print(np.vstack([A, B, B]))

[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]]
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]
 [11 22 33]
 [44 55 66]]


In [70]:
np.hstack([A, B])

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [71]:
np.vstack([a, a])

array([[33,  2,  3],
       [33,  2,  3]])

In [72]:
np.hstack([a, a])

array([33,  2,  3, 33,  2,  3])

## Некоторые операции с векторами

In [73]:
v = np.array([2, 5, 1, 9])
print(v.min())
print(v.max())
print(v.mean())
print(v.std())
print(v.sum())

1
9
4.25
3.112474899497183
17


In [74]:
# А можно так:
print(np.min(v))   
print(np.max(v))
print(np.mean(v))
print(np.std(v))
print(np.sum(v))
print(np.median(v))

1
9
4.25
3.112474899497183
17
3.5


In [75]:
w = np.sort(v)
print(w)
print(v)

[1 2 5 9]
[2 5 1 9]


In [76]:
v

array([2, 5, 1, 9])

In [77]:
v.sort()
v

array([1, 2, 5, 9])

In [78]:
x = [3, 1, 2, 3]
print(sorted(x))
print(x)

[1, 2, 3, 3]
[3, 1, 2, 3]


In [79]:
type(sorted(a))

list

## Линейная алгебра

In [80]:
A = np.array([[1, 2, 3], [4, 1, 6], [7, 2, 0]])
A

array([[1, 2, 3],
       [4, 1, 6],
       [7, 2, 0]])

In [81]:
x = np.array([[1], [2], [-1]])
x

array([[ 1],
       [ 2],
       [-1]])

In [82]:
print(A.T)

[[1 4 7]
 [2 1 2]
 [3 6 0]]


In [83]:
A.T[1, 0] = 10

In [84]:
A

array([[ 1, 10,  3],
       [ 4,  1,  6],
       [ 7,  2,  0]])

In [85]:
B = A.transpose()

In [86]:
B[1, 0] = 300

In [87]:
A

array([[  1, 300,   3],
       [  4,   1,   6],
       [  7,   2,   0]])

In [88]:
print(A)
print(x)
b = A * x
print(b)

[[  1 300   3]
 [  4   1   6]
 [  7   2   0]]
[[ 1]
 [ 2]
 [-1]]
[[  1 300   3]
 [  8   2  12]
 [ -7  -2   0]]


In [89]:
print(np.dot(A, x))

[[598]
 [  0]
 [ 11]]


In [90]:
print(np.dot(x.T, A.T))

[[598   0  11]]


In [91]:
print(x.shape)
print(A.shape)

(3, 1)
(3, 3)


In [92]:
B = np.dot(A, A)

In [93]:
print(A)
print(B)

[[  1 300   3]
 [  4   1   6]
 [  7   2   0]]
[[1222  606 1803]
 [  50 1213   18]
 [  15 2102   33]]


In [94]:
np.dot(A, np.dot(A, B)) # A*(A*B)

array([[1550629, 5265516, 2273673],
       [ 122020, 1539505,  112578],
       [ 123925, 2628182,   65970]])

In [95]:
A.dot(A).dot(B)

array([[1550629, 5265516, 2273673],
       [ 122020, 1539505,  112578],
       [ 123925, 2628182,   65970]])

In [96]:
xx = np.array([1, 2, -1])
print(np.dot(xx, A))
print(np.dot(A, xx))

[  2 300  15]
[598   0  11]


In [97]:
print(xx.shape, A.shape)

(3,) (3, 3)


In [98]:
np.expand_dims(xx, axis=0)

array([[ 1,  2, -1]])

In [99]:
print("A = \n", A)
print("x = \n", x)
print("b = \n", b)

A = 
 [[  1 300   3]
 [  4   1   6]
 [  7   2   0]]
x = 
 [[ 1]
 [ 2]
 [-1]]
b = 
 [[  1 300   3]
 [  8   2  12]
 [ -7  -2   0]]


In [100]:
import scipy.linalg as linalg # есть также numpy.linalg

In [101]:
x = linalg.solve(A, b)
print(x)

[[-0.99618775 -0.57040743  0.00285919]
 [-0.01334286  0.99642602 -0.01000715]
 [ 1.99968231  0.54753395  1.99976173]]


In [102]:
linalg.det(A)

12591.0

In [103]:
linalg.inv(A)

array([[-9.53061711e-04,  4.76530855e-04,  1.42720991e-01],
       [ 3.33571599e-03, -1.66785799e-03,  4.76530855e-04],
       [ 7.94218092e-05,  1.66626956e-01, -9.52267493e-02]])

In [104]:
linalg.pinv(A)

array([[-9.53061711e-04,  4.76530855e-04,  1.42720991e-01],
       [ 3.33571599e-03, -1.66785799e-03,  4.76530855e-04],
       [ 7.94218092e-05,  1.66626956e-01, -9.52267493e-02]])

## Метод наименьших квадратов

In [105]:
A = np.array([[1, 2], [3, 4], [1, 2]])
print(A)

[[1 2]
 [3 4]
 [1 2]]


In [106]:
b = np.array([1, 2, 3])
print(b)

[1 2 3]


In [107]:
x = linalg.solve(A, b) # не работает
print(x)

ValueError: Input a needs to be a square matrix.

In [108]:
x, _, _, _ = linalg.lstsq(A, b)
print(x)

[-2.  2.]


In [109]:
x, residuals, rank, sv = linalg.lstsq(A, b)

print("x = \n", x)
print("residuals = ", residuals)
print("rank = ", rank)
print("sv = ", sv) # Сингулярные числа

x = 
 [-2.  2.]
residuals =  2.0000000000000004
rank =  2
sv =  [5.89660208 0.47967068]


In [110]:
pinvA = linalg.pinv(A)
print(pinvA)
print(np.dot(pinvA, b))

[[-1.    1.   -1.  ]
 [ 0.75 -0.5   0.75]]
[-2.  2.]


## Собственные числа и собственные векторы

In [111]:
A = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)

[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [112]:
evalues, evectors = linalg.eig(A)
print(evalues)
print(evectors)

[1.+0.j 4.+0.j 1.+0.j]
[[-0.81649658  0.57735027  0.381008  ]
 [ 0.40824829  0.57735027 -0.81590361]
 [ 0.40824829  0.57735027  0.43489561]]


In [113]:
Q = evectors

In [114]:
# Проверка:
linalg.inv(Q).dot(A).dot(Q)

array([[ 1.00000000e+00,  1.04700284e-15, -6.92636774e-17],
       [ 6.74596531e-16,  4.00000000e+00, -5.03593729e-16],
       [-4.39801323e-17, -9.52089873e-17,  1.00000000e+00]])

In [115]:
Q.T.dot(Q) 

array([[ 1.00000000e+00, -5.33954722e-17, -4.66637596e-01],
       [-5.33954722e-17,  1.00000000e+00,  9.61461727e-17],
       [-4.66637596e-01,  9.61461727e-17,  1.00000000e+00]])

In [116]:
J = np.array([[2, 1, 0], [0, 2, 1], [0, 0, 2]])
print(J)

[[2 1 0]
 [0 2 1]
 [0 0 2]]


In [117]:
D, Q = linalg.eig(J)
print(D)
print(Q)

[2.+0.j 2.+0.j 2.+0.j]
[[ 1.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  4.44089210e-16 -4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  1.97215226e-31]]


## Сингулярное разложение

In [118]:
A = np.array([[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]])
print(A)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [119]:
U, S, V = linalg.svd(A)

In [120]:
print("U = \n", U)
print("S = \n", S)
print("V = \n", V)

U = 
 [[-0.40361757  0.73286619  0.52407556  0.15920053]
 [-0.46474413  0.28984978 -0.81742848  0.17835548]
 [-0.52587069 -0.15316664  0.06263029 -0.83431256]
 [-0.58699725 -0.59618305  0.23072264  0.49675655]]
S = 
 [2.54368356e+01 1.72261225e+00 4.20733283e-16]
V = 
 [[-0.20673589 -0.51828874 -0.82984158]
 [-0.88915331 -0.25438183  0.38038964]
 [ 0.40824829 -0.81649658  0.40824829]]


In [121]:
# Проверка:
print("U'*A*V' = \n", np.dot(np.dot(U.T, A), V.T)) 

U'*A*V' = 
 [[ 2.54368356e+01 -1.28618713e-15  3.37120683e-15]
 [ 6.22694430e-17  1.72261225e+00  4.27068596e-16]
 [ 2.99023320e-16  4.09115770e-16  2.26623326e-16]
 [-1.28918944e-15 -2.82945976e-16 -1.81298661e-16]]


In [122]:
A = np.array([[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]])
b = np.array([[1], [1], [1], [2]])
print(A)
print(b)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[1]
 [1]
 [1]
 [2]]
