# Матрицы и векторы

Подключаем необходимые библиотеки:
```python
from numpy import *
from matplotlib.pyplot import *
```

Все это (и даже больше) делает magic-команда
```python
%pylab
```

Лучше поступать так:
```python
import numpy as np
import matplotlib.pyplot as plt
```

Вместо этого можно выполнить команду
```python
%pylab --no-import-all
```

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Создание массива (вектора)

In [2]:
x = [1,2,3,2,3,4]
type(x)

list

In [3]:
x = np.array((1, 2.0, -1))
print x

[ 1.  2. -1.]


In [4]:
print type(x)
print x.ndim  # Количество размерностей массива
print x.shape # Размеры
print x.dtype # Тип элементов

<type 'numpy.ndarray'>
1
(3L,)
float64


In [5]:
x = np.array([1, 2, -1], dtype = 'float')
print x

[ 1.  2. -1.]


In [6]:
print type(x)
print x.shape
print x.dtype

<type 'numpy.ndarray'>
(3L,)
float64


## Двумерные массивы

In [7]:
A = np.array([[1, 2, 3], [4, 1, 6], [7, 2, 0]])
print A

[[1 2 3]
 [4 1 6]
 [7 2 0]]


In [8]:
#A = [1, 2, 3; 4, 1, 6; 7, 2, 0] # А так в MATLAB

In [9]:
print type(A)
print A.ndim 
print A.shape
print A.dtype

<type 'numpy.ndarray'>
2
(3L, 3L)
int32


## Элементы и срезы

In [10]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
A[1]

array([5, 6, 7, 8])

In [12]:
A[1][2]

7

In [13]:
A[1, 2] # То же самое

7

In [14]:
A[1,3] = 333
A

array([[  1,   2,   3,   4],
       [  5,   6,   7, 333],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [15]:
A[1:4, 0:2] # не так: A[1:4][0:2]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [16]:
A[1:4]

array([[  5,   6,   7, 333],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [17]:
A[1:4][0:2]

array([[  5,   6,   7, 333],
       [  9,  10,  11,  12]])

In [18]:
B = A[1:4]
B[0:2]

array([[  5,   6,   7, 333],
       [  9,  10,  11,  12]])

In [19]:
A[1:4, 0:2] = [[1, 3], [5, 0], [0, 0]]
#A[1:4, 0:2] = 0
print A

[[  1   2   3   4]
 [  1   3   7 333]
 [  5   0  11  12]
 [  0   0  15  16]]


In [20]:
B = A[1:4:2][::2]
B

array([[  1,   3,   7, 333]])

In [21]:
B = A[1:4, 0:2]
B[1, 0] = 555    # Меняет и массив A (в отличие от срезов в списках) 
A

array([[  1,   2,   3,   4],
       [  1,   3,   7, 333],
       [555,   0,  11,  12],
       [  0,   0,  15,  16]])

In [22]:
x = np.array([1, 2, -3, 4, -2, 2])
#y = np.array([-1, 0, -3, 4, -2, 1])
x > 0

array([ True,  True, False,  True, False,  True], dtype=bool)

In [23]:
x[np.array([ True,  True, False,  True, False,  True], dtype='bool')]

array([1, 2, 4, 2])

In [24]:
x[x > 0] = 111
x

array([111, 111,  -3, 111,  -2, 111])

In [25]:
A = np.array([[1,  2, -3], [4, -2,  2]])
A

array([[ 1,  2, -3],
       [ 4, -2,  2]])

In [26]:
A > 0

array([[ True,  True, False],
       [ True, False,  True]], dtype=bool)

In [27]:
A[:, 2:]

array([[-3],
       [ 2]])

In [28]:
A[A > 0]

array([1, 2, 4, 2])

In [29]:
a = 11*np.array(range(0, 10))
print a
print a[[1, 3, 5]]   # Так тоже можно выделять подмассивы (со списками этот фокус не прокатит)

[ 0 11 22 33 44 55 66 77 88 99]
[11 33 55]


In [30]:
np.arange(0, 10) # эквивалентно np.array(range(0, 10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
color = np.array(['red', 'blue'])
color[[1, 0, 1, 0, 1, 0]]
#type(color)
#color.dtype

array(['blue', 'red', 'blue', 'red', 'blue', 'red'], 
      dtype='|S4')

## Создание векторов и матриц

In [32]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(2, 10, .3)

array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7,  8. ,  8.3,
        8.6,  8.9,  9.2,  9.5,  9.8])

In [34]:
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [35]:
np.random.seed(42) # use random.seed() to randomize
np.random.rand(5)

array([ 0.37454012,  0.95071431,  0.73199394,  0.59865848,  0.15601864])

In [36]:
np.random.rand(3, 5)

array([[ 0.15599452,  0.05808361,  0.86617615,  0.60111501,  0.70807258],
       [ 0.02058449,  0.96990985,  0.83244264,  0.21233911,  0.18182497],
       [ 0.18340451,  0.30424224,  0.52475643,  0.43194502,  0.29122914]])

In [37]:
a = -1
b = 1
np.random.rand(2, 5)*(b-a) + a

array([[ 0.22370579, -0.72101228, -0.4157107 , -0.26727631, -0.08786003],
       [ 0.57035192, -0.60065244,  0.02846888,  0.18482914, -0.90709917]])

In [38]:
for i in range(10):
    print np.random.randint(0, 10)

2
6
4
8
6
1
3
8
1
9


In [39]:
np.random.randint(0, 10, (3, 5))

array([[8, 9, 4, 1, 3],
       [6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5]])

In [40]:
np.random.randn(5) # Нормальная случайная величина с мат.ожиданием - 0, сигма = 1

array([ 0.3229998 , -1.39341694, -2.17833425, -1.04389641,  0.17269371])

In [41]:
sigma = 3;
mu = 5
sigma*np.random.randn(5) + mu 

array([ 5.9725963 ,  7.23757863, -0.50974972,  6.69339272,  5.076502  ])

In [42]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [43]:
Z = np.zeros([3, 5])
print Z

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [44]:
np.ones(6)

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [45]:
I = np.ones((2, 4))
print I

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [46]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [47]:
E = np.eye(3, 6)
print E

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]]


## Манипулирование с матрицами

In [48]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [49]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [50]:
np.array([1, 2, 3]) / np.array([4, 5, 6])

array([0, 0, 0])

In [51]:
3*[1, 2, 3]

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [52]:
3*np.array([1, 2, 3])

array([3, 6, 9])

In [53]:
np.array([1, 2, 3])/5.0

array([ 0.2,  0.4,  0.6])

In [54]:
np.array([1, 2, 3]) + 5.0

array([ 6.,  7.,  8.])

In [55]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

In [56]:
x = np.linspace(-np.pi, np.pi, 20)
2*np.sin(x) + x**2

array([ 9.8696044 ,  7.25175251,  4.92299006,  2.94606356,  1.36929402,
        0.22134059, -0.49190506, -0.78795721, -0.70583817, -0.30184956,
        0.3565288 ,  1.19795141,  2.15493843,  3.17118825,  4.20767856,
        5.24689508,  6.29472948,  7.37984091,  8.55055038,  9.8696044 ])

In [57]:
a = np.arange(1, 13)
print a
A = a.reshape((3, 4))
print A

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
A[2, 1] = 111
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 111,  11,  12])

In [59]:
A = np.arange(1, 7).reshape([2, 3])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
B = 11*np.arange(1, 7).reshape([2, 3])
B

array([[11, 22, 33],
       [44, 55, 66]])

In [61]:
a = np.array([1, 2, 3])
np.concatenate([a, a, a])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [62]:
np.concatenate([A, A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
print A
print B
print np.vstack([A, B, B])

[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]]
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]
 [11 22 33]
 [44 55 66]]


In [64]:
np.hstack([A, B])

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [65]:
np.vstack([a, a])

array([[1, 2, 3],
       [1, 2, 3]])

In [66]:
np.hstack([a, a])

array([1, 2, 3, 1, 2, 3])

## Некоторые операции с векторами

In [67]:
v = np.array([2, 5, 1, 9])
print v.min()
print v.max()
print v.mean()
print v.std()
print v.sum()

1
9
4.25
3.1124748995
17


In [68]:
# А можно так:
print np.min(v)    
print np.max(v)
print np.mean(v)
print np.std(v)
print np.sum(v)
print np.median(v)

1
9
4.25
3.1124748995
17
3.5


In [69]:
w = np.sort(v)
print w
print v

[1 2 5 9]
[2 5 1 9]


In [70]:
v

array([2, 5, 1, 9])

In [71]:
v.sort()
v

array([1, 2, 5, 9])

In [72]:
x=[3, 1, 2, 3]
print sorted(x)
print x

[1, 2, 3, 3]
[3, 1, 2, 3]


## Линейная алгебра

In [73]:
A = np.array([[1, 2, 3], [4, 1, 6], [7, 2, 0]])
A

array([[1, 2, 3],
       [4, 1, 6],
       [7, 2, 0]])

In [74]:
x = np.array([[1], [2], [-1]])
x

array([[ 1],
       [ 2],
       [-1]])

In [75]:
print A.T

[[1 4 7]
 [2 1 2]
 [3 6 0]]


In [76]:
A

array([[1, 2, 3],
       [4, 1, 6],
       [7, 2, 0]])

In [77]:
A.transpose()

array([[1, 4, 7],
       [2, 1, 2],
       [3, 6, 0]])

In [78]:
A

array([[1, 2, 3],
       [4, 1, 6],
       [7, 2, 0]])

In [79]:
b = A*x
print b

[[ 1  2  3]
 [ 8  2 12]
 [-7 -2  0]]


In [80]:
b = np.dot(A, x)
print b

[[ 2]
 [ 0]
 [11]]


In [81]:
print np.dot(x.T, A)

[[ 2  2 15]]


In [82]:
B = np.dot(A, A)

In [83]:
print A
print B

[[1 2 3]
 [4 1 6]
 [7 2 0]]
[[30 10 15]
 [50 21 18]
 [15 16 33]]


In [84]:
np.dot(A, np.dot(A, B)) # A*(A*B)

array([[1625,  750, 1125],
       [2820, 1229, 1722],
       [1745, 1014, 1602]])

In [85]:
A.dot(A).dot(B)

array([[1625,  750, 1125],
       [2820, 1229, 1722],
       [1745, 1014, 1602]])

In [86]:
xx = np.array([1, 2, -1])
print np.dot(xx, A)
print np.dot(A, xx)

[ 2  2 15]
[ 2  0 11]


In [87]:
print "A = \n", A
print "x = \n", x
print "b = \n", b

A = 
[[1 2 3]
 [4 1 6]
 [7 2 0]]
x = 
[[ 1]
 [ 2]
 [-1]]
b = 
[[ 2]
 [ 0]
 [11]]


In [92]:
import scipy.linalg as linalg # есть также numpy.linalg

In [94]:
x = linalg.solve(A, b)
print x

[[ 1.]
 [ 2.]
 [-1.]]


In [95]:
linalg.det(A)

75.0

In [96]:
linalg.inv(A)

array([[-0.16      ,  0.08      ,  0.12      ],
       [ 0.56      , -0.28      ,  0.08      ],
       [ 0.01333333,  0.16      , -0.09333333]])

In [97]:
linalg.pinv(A)

array([[-0.16      ,  0.08      ,  0.12      ],
       [ 0.56      , -0.28      ,  0.08      ],
       [ 0.01333333,  0.16      , -0.09333333]])

## Метод наименьших квадратов

In [98]:
A = np.array([[1, 2], [3, 4], [1, 2]])
print A

[[1 2]
 [3 4]
 [1 2]]


In [99]:
b = np.array([1,2,3])
print b

[1 2 3]


In [100]:
x = linalg.solve(A, b) # не работает
print x

ValueError: expected square matrix

In [101]:
x, _, _, _ = linalg.lstsq(A, b)
print x

[-2.  2.]


In [102]:
x, residuals, rank, sv = linalg.lstsq(A, b)

print "x = \n", x
print "residuals = ", residuals
print "rank = ", rank
print "sv = ", sv # Сингулярные числа

x = 
[-2.  2.]
residuals =  2.0
rank =  2
sv =  [ 5.89660208  0.47967068]


In [103]:
pinvA = linalg.pinv(A)
print pinvA 
print np.dot(pinvA, b)

[[-1.    1.   -1.  ]
 [ 0.75 -0.5   0.75]]
[-2.  2.]


## Собственные числа и собственные векторы

In [104]:
A = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print A

[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [105]:
evalues, evectors = linalg.eig(A)
print evalues
print evectors

[ 1.+0.j  4.+0.j  1.+0.j]
[[-0.81649658  0.57735027 -0.32444284]
 [ 0.40824829  0.57735027 -0.48666426]
 [ 0.40824829  0.57735027  0.81110711]]


In [106]:
Q = evectors

In [107]:
# Проверка:
linalg.inv(Q).dot(A).dot(Q)

array([[  1.00000000e+00,   4.23272528e-16,   0.00000000e+00],
       [  5.55111512e-16,   4.00000000e+00,   2.22044605e-16],
       [  5.55111512e-17,  -4.99600361e-16,   1.00000000e+00]])

In [108]:
Q.T.dot(Q) 

array([[  1.00000000e+00,  -1.38777878e-16,   3.97359707e-01],
       [ -1.38777878e-16,   1.00000000e+00,  -5.55111512e-17],
       [  3.97359707e-01,  -5.55111512e-17,   1.00000000e+00]])

In [109]:
J = np.array([[2, 1, 0], [0, 2, 1], [0, 0, 2]])
print J

[[2 1 0]
 [0 2 1]
 [0 0 2]]


In [110]:
D, Q = linalg.eig(J)
print D
print Q

[ 2.+0.j  2.+0.j  2.+0.j]
[[  1.00000000e+00  -1.00000000e+00   1.00000000e+00]
 [  0.00000000e+00   4.44089210e-16  -4.44089210e-16]
 [  0.00000000e+00   0.00000000e+00   1.97215226e-31]]


## Сингулярное разложение

In [111]:
A = np.array([[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]])
print A

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [113]:
U, S, V = linalg.svd(A)

In [114]:
print "U = \n", U
print "S = \n", S
print "V = \n", V

U = 
[[-0.40361757 -0.73286619 -0.28193879 -0.46958548]
 [-0.46474413 -0.28984978  0.72592673  0.4159692 ]
 [-0.52587069  0.15316664 -0.6060371   0.57681802]
 [-0.58699725  0.59618305  0.16204916 -0.52320175]]
S = 
[  2.54368356e+01   1.72261225e+00   1.44339459e-15]
V = 
[[-0.20673589 -0.51828874 -0.82984158]
 [ 0.88915331  0.25438183 -0.38038964]
 [-0.40824829  0.81649658 -0.40824829]]


In [115]:
# Проверка:
print "U'*A*V' = \n", np.dot(np.dot(U.T, A), V.T) 

U'*A*V' = 
[[  2.54368356e+01   0.00000000e+00  -1.77635684e-15]
 [ -3.55271368e-15   1.72261225e+00   5.55111512e-17]
 [  2.85541514e-15   4.34993495e-16   3.17272656e-16]
 [ -1.28918944e-15   2.82945976e-16   1.81298661e-16]]


In [116]:
A = np.array([[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]])
b = np.array([[1], [1], [1], [2]])
print A
print b

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[1]
 [1]
 [1]
 [2]]
